import type { SourceKind } from "@/components/source-badge"

export type EstimateRow = {
  id: number
  description: string
  note?: string
  qty: string
  unit: string
  unitPrice: string
  labor: string
  material: string
  equip: string
  sub: string
  mu: string
  total: string
  source: SourceKind
}

export const estimateRows: EstimateRow[] = [
  {
    id: 1,
    description: "Mobilization",
    qty: "1",
    unit: "LS",
    unitPrice: "$85,000.00",
    labor: "—",
    material: "—",
    equip: "—",
    sub: "—",
    mu: "10",
    total: "$85,000",
    source: "official",
  },
  {
    id: 2,
    description: "Traffic Control System",
    qty: "1",
    unit: "LS",
    unitPrice: "$62,000.00",
    labor: "—",
    material: "—",
    equip: "—",
    sub: "$56,400",
    mu: "10",
    total: "$62,000",
    source: "manual",
  },
  {
    id: 3,
    description: "Clearing & Grubbing",
    qty: "1",
    unit: "LS",
    unitPrice: "$28,500.00",
    labor: "$12,400",
    material: "$2,100",
    equip: "$11,300",
    sub: "—",
    mu: "10",
    total: "$28,500",
    source: "official",
  },
  {
    id: 4,
    description: "Roadway Excavation",
    qty: "8,450",
    unit: "CY",
    unitPrice: "$14.20",
    labor: "$4.10",
    material: "$0.60",
    equip: "$7.30",
    sub: "—",
    mu: "10",
    total: "$119,990",
    source: "official",
  },
  {
    id: 5,
    description: "Class 2 Aggregate Base",
    qty: "6,200",
    unit: "TON",
    unitPrice: "$52.75",
    labor: "$6.20",
    material: "$38.10",
    equip: "$4.40",
    sub: "—",
    mu: "10",
    total: "$327,050",
    source: "official",
  },
  {
    id: 6,
    description: "HMA Type A",
    qty: "4,850",
    unit: "TON",
    unitPrice: "$128.00",
    labor: "$18.00",
    material: "$86.00",
    equip: "$12.00",
    sub: "—",
    mu: "10",
    total: "$620,800",
    source: "reviewed",
  },
  {
    id: 7,
    description: 'Cold Plane AC (2")',
    qty: "12,300",
    unit: "SY",
    unitPrice: "$6.40",
    labor: "$1.10",
    material: "—",
    equip: "$4.20",
    sub: "—",
    mu: "10",
    total: "$78,720",
    source: "official",
  },
  {
    id: 8,
    description: '18" RCP Class III',
    qty: "640",
    unit: "LF",
    unitPrice: "$148.00",
    labor: "$52.00",
    material: "$61.00",
    equip: "$22.00",
    sub: "—",
    mu: "10",
    total: "$94,720",
    source: "reviewed",
  },
  {
    id: 9,
    description: "Drainage Inlet (Type GO)",
    qty: "12",
    unit: "EA",
    unitPrice: "$6,850.00",
    labor: "$2,100",
    material: "$3,400",
    equip: "$730",
    sub: "—",
    mu: "10",
    total: "$82,200",
    source: "official",
  },
  {
    id: 10,
    description: "Adjust Manhole to Grade",
    qty: "9",
    unit: "EA",
    unitPrice: "$1,450.00",
    labor: "$520",
    material: "$480",
    equip: "$320",
    sub: "—",
    mu: "10",
    total: "$13,050",
    source: "official",
  },
  {
    id: 11,
    description: "Thermoplastic Traffic Stripe",
    note: "Sub quote: Valley Striping",
    qty: "24,500",
    unit: "LF",
    unitPrice: "$1.85",
    labor: "—",
    material: "—",
    equip: "—",
    sub: "$1.68",
    mu: "10",
    total: "$45,325",
    source: "manual",
  },
  {
    id: 12,
    description: "Pavement Marking Thermo",
    qty: "1,850",
    unit: "SF",
    unitPrice: "$8.20",
    labor: "—",
    material: "—",
    equip: "—",
    sub: "$7.45",
    mu: "10",
    total: "$15,170",
    source: "reviewed",
  },
  {
    id: 13,
    description: "Roadside Sign (One Post)",
    qty: "14",
    unit: "EA",
    unitPrice: "$685.00",
    labor: "$210",
    material: "$340",
    equip: "$75",
    sub: "—",
    mu: "10",
    total: "$9,590",
    source: "official",
  },
  {
    id: 14,
    description: "Erosion Control (Hydroseed)",
    qty: "45,000",
    unit: "SF",
    unitPrice: "$0.28",
    labor: "—",
    material: "—",
    equip: "—",
    sub: "$0.25",
    mu: "10",
    total: "$12,600",
    source: "official",
  },
  {
    id: 15,
    description: "Minor Concrete (Curb & Gutter)",
    qty: "2,150",
    unit: "LF",
    unitPrice: "$58.00",
    labor: "—",
    material: "—",
    equip: "—",
    sub: "$52.70",
    mu: "10",
    total: "$124,700",
    source: "official",
  },
]

export const comingSoonSources = [
  "Labor production rates",
  "Material prices",
  "Equipment rental rates",
  "Supplier pricing",
  "Prevailing wage database",
  "Regional cost adjustment",
]
