// The verification disclaimer, defined once (step 43).
//
// This text appears on every file the product generates *and* in the Terms of
// Service. Those two have to say the same thing — a disclaimer on an export
// that the Terms don't back, or Terms promising a warning the exports don't
// actually carry, is worse than having neither. So both read from here rather
// than each keeping their own copy to drift apart.
//
// Deliberately plain, not legalese: this is the line an estimator reads at
// 4pm on bid day, and the point is that they act on it.

/** Shown on every generated file and quoted verbatim in the Terms of Service. */
export const VERIFICATION_DISCLAIMER =
  "Constimator is a checking aid, not a substitute for your own review. You are solely responsible for verifying every quantity, price, and condition in this document against the original source documents before submitting a bid. AI-extracted data is not guaranteed to be accurate or complete."

/** Second line on exports only — the Terms carry this obligation in their own words rather than as a file footer. */
export const EXPORT_FOOTER_NOTE =
  "Generated by Constimator. Check figures against the source documents before use."

/**
 * The count that goes on the face of an export when anything in it is
 * unconfirmed. Returns null when there is nothing to warn about, so a callers'
 * "should I show the banner" question is just a null check.
 *
 * Worded as an instruction rather than a statistic — "3 unverified" invites
 * being read as a minor tally, where naming what it means invites acting on it.
 */
export function unverifiedNotice(unverifiedCount: number, totalCount: number): string | null {
  if (unverifiedCount <= 0) return null

  const items = unverifiedCount === 1 ? "item has" : "items have"
  const of = totalCount > 0 ? ` of ${totalCount}` : ""

  return `UNVERIFIED DATA — ${unverifiedCount}${of} ${items} not been confirmed against the original documents. Confirm them in Constimator before relying on this file.`
}

/** Short form for a filename-adjacent label or a PDF header strap, where the full notice is too long. */
export function unverifiedBadge(unverifiedCount: number): string | null {
  if (unverifiedCount <= 0) return null
  return `${unverifiedCount} unverified`
}
